
JTA_I18N.addResourceBundle('jTweetsAnywhere', 'es',
{
	'More': 'Ver todos los Tuits',
	'Prev': 'Zur&uuml;ck',
	'Next': 'Weiter',
	'%count% new tweet': '%count% nuevo tuit',
	'%count% new tweets': '%count% nuevos tuits',
	"What's happening?": "Qu&eacute; est&aacute; pasando",
	'%secs% second ago': '%secs% segundo atr&aacute;s',
	'%secs% seconds ago': '%secs% segundos atr&aacute;s',
	'%mins% minute ago': '%mins% minuto atr&aacute;s',
	'%mins% minutes ago': '%mins% minutos atr&aacute;s',
	'%hours% hour ago': '%hours% hora atr&aacute;s',
	'%hours% hours ago': '%hours% horas atr&aacute;s',
	'%days% day ago': '%days% d&iacute;a atr&aacute;s',
	'%days% days ago': '%days% d&iacute;as atr&aacute;s',
	'via': 'via',
	'on Twitter': 'en Twitter',
	'Reply': 'Reply',
	'Retweet': 'Retweet',
	'Favorite': 'Favoritos',
	'here': 'aqui',
	'in reply to': 'in reply to',
	'from': 'de',
	' and %rtc% other': ' y %rtc% otros',
	' and %rtc% others': ' y %rtc% otros',
	'Retweeted by': 'Retweeted por',
	'Sign out': 'Salir',
	'loading': 'cargando',
	'ERROR': 'ERROR',

	'$$monthNames': [ "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic" ]
});
